name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client:
    name: Frontend - React
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

  server:
    name: Backend - Express
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test